server:
  port: 8971
  servlet:
    context-path: ~
  tomcat:
    uri-encoding: UTF-8
   
eureka:
  instance:
    hostname: 127.0.0.1
    preferIfAddress: false
    statusPageUrlPath: ${server.servlet.context-path}/project/default
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
  client:
    serviceUrl.defaultZone: http://127.0.0.1:8970/eureka
    
spring:
  application:
    name: ibyg-cloud-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:cloud-config
  main:
    bannerMode: "off"
          